const PollTypes = {
    ADD_POLL:"ADD_POLL",
    RESET_POLL:"RESET_POLL",
    UPDATE_QUESTION:"UPDATE_QUESTION",
    REMOVE_AN_ANSWER:"REMOVE_AN_ANSWER",
    VOTING:"VOTING",
    UPDATE_SINGLE_ANSWER:"UPDATE_SINGLE_ANSWER",
    REFRESH_POLL_DATA:"REFRESH_POLL_DATA",
    SWITCH_ROLE:"SWITCH_ROLE"
}

export default PollTypes;